---
abstract: 'Perl6 style Junction operators in Perl5'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
  - 'Carl Franks'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Keyword-Junction
requires:
  Sub::Exporter::Progressive: 0.001006
  Test::More: 0
  syntax: 0
resources:
  bugtracker: https://github.com/frioux/Syntax-Keyword-Junction/issues
  repository: git://github.com/frioux/Syntax-Keyword-Junction.git
version: 0.003002
