---
abstract: 'Perl6 style Junction operators in Perl5'
author:
  - 'Arthur Axel "fREW" Schmidt <frioux+cpan@gmail.com>'
  - 'Carl Franks'
build_requires:
  Test::More: '0.88'
  Test::Requires: '0.07'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Syntax-Keyword-Junction
requires:
  Sub::Exporter::Progressive: '0.001006'
  parent: '0'
  syntax: '0'
resources:
  homepage: https://github.com/frioux/Syntax-Keyword-Junction
  repository: https://github.com/frioux/Syntax-Keyword-Junction.git
version: '0.003008'
